# Generated by Django 3.2.8 on 2021-11-27 00:13

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('header1', models.CharField(max_length=255)),
                ('header2', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to=mainapp.models.upload_file_path)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
