# Generated by Django 3.2.8 on 2021-11-27 00:27

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='scholarship_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.upload_file_path),
        ),
    ]
