# Generated by Django 3.2.8 on 2021-11-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_scholarship_scholarship_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='scholarship_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
