# Generated by Django 3.2.8 on 2021-11-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='grade_pont_average',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
