# Generated by Django 3.2.8 on 2021-11-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_userprofile_grade_pont_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='scholarship_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='scholarship_employment',
            field=models.BooleanField(default=False),
        ),
    ]
