# Generated by Django 3.2.8 on 2021-11-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20211127_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='gpa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
