# Generated by Django 3.2.8 on 2021-11-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_remove_scholarship_scholarship_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='scholarship_budget',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='scholarship_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
