# Generated by Django 3.2.8 on 2021-11-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20211127_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='course',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
